name: Go

on:
  push:
    branches: [ master ]
    paths:
    - '!README.md/**'
  pull_request:
    branches: [ master ]
    paths:
    - '!README.md/**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Test
      run: go test ./...
      
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    #runs-on: ubuntu-latest
    steps:

    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build  ${{ matrix.go-version }}
      run: go build -v .

    - name: Create package (windows)
      if: startsWith(matrix.platform, 'windows')
      run: |
        xcopy fdd.exe pkg\ && xcopy config.json pkg\
        
    - name: Create package (ubuntu)
      if: startsWith(matrix.platform, 'ubuntu')
      run: |
        mkdir -p pkg && cp fdd config.json ./pkg

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: FDD ${{ matrix.go-version }}
        # Directory containing files to upload
        path: pkg
